### ISSUE TITLE
Serial /dev/tty.usermodem* failed name check, skipping 

### ISSUE THREAD

**Issue by AnXelion** [eembc/benchmark-runner-ml#6]
Hi,

I was trying to run [reference_submissions](https://github.com/mlcommons/tiny/tree/master/v0.1/reference_submissions) provided by [tinyML](https://github.com/mlcommons/tiny) on [NUMAKER-IOT-M487,](https://os.mbed.com/platforms/NUMAKER-IOT-M487/) which is an MBed supported board. 

However, after flashing the bin file to the board, EEMBC Benchmark Framework responded
`pnp: Serial /dev/tty.usermodem14202 failed name check, skipping`

I could `screen /dev/tty.usermodem14202 9600` and see the following messages

```
m-timestamp-mode-energy
m-lap-us-0
Initialized
m-init-done
m-ready
```

The board was connected to my MacBook running macOS Mojave v10.14.6 and EEMBC Benchmark Framework v3.0.

Did I miss any settings so that EEMBC Benchmark Framework v3.0 couldn't recognize the board?

Thanks!

**Comment by petertorelli** [comment]
Hi @AnXelion,

By default, the runner scans for direct-connected devices at 115200 baud. So if the DUT is plugged into the Host PC directly, it should use 115200. You can recompile the firmware to change this, or you can change your $HOME/.eembc.ini file's `dut-baud=115200` to `dut-baud=9600` as shown [here](https://github.com/eembc/benchmark-runner-ml#custom-configuration). However, if you are bringing up the device for performance mode (and accuracy) you should stick with 115200 (or higher).

Let me know if that solves it.

Peter

**Comment by petertorelli** [comment]
@AnXelion Did that work? Can we close this?

**Comment by AnXelion** [comment]
Hi, 

Sorry for the late reply. I am going to following the guide you kindly provided after the weekend. I think we can close this. If there is any further update, I will reopen and post it here. Thanks you.
